#!/bin/sh
# dev-plugin-link.sh — stop having to exit and restart Claude Code after every hook edit.
#
# THE PROBLEM. Claude Code COPIES a plugin into ~/.claude/plugins/cache/<name>/<version>/ and a
# session pins one version directory at startup. The hook the harness executes is that copy, never
# your working tree. So "I fixed the hook" and "the hook is fixed" are two different statements
# until you restart. (Observed 2026-07-09: the running session's cached hook was 242 lines while
# the repo's was 268 — a whole day of hook changes were inert.)
#
# WHAT DOESN'T NEED THIS. Data is already live: forge-ask-all discovers *.rvf at query time, so a
# rebuilt KB is searchable immediately, no restart. Only CODE is pinned.
#
# THE FIX. Replace the cached hook scripts with a two-line shim that `exec`s the working tree's
# copy, keeping the original as <name>.frozen.sh. The next prompt runs your edits. Reversible.
#
#   sh scripts/dev-plugin-link.sh --link      # working tree becomes the live hook
#   sh scripts/dev-plugin-link.sh --status    # what is linked, what is frozen
#   sh scripts/dev-plugin-link.sh --unlink    # restore the pristine cached copies
#
# SCOPE + SAFETY
#   · Only touches ~/.claude/plugins/cache/ruvnet-brain/**/scripts/*.sh — never the repo, never
#     settings.json, never a LaunchAgent.
#   · The shim falls back to the frozen copy if the repo is missing, so deleting the repo cannot
#     silently disable grounding. The harness invokes the hook with `|| true`, meaning a broken
#     hook fails SILENTLY — hence the fallback, and hence --status.
#   · Set RUVNET_BRAIN_DEV=0 in the environment to bypass the shim without unlinking.
#   · This is a DEVELOPER convenience for the person who edits the plugin. Users never run it.
#
# The MCP server (mcp/) is a long-lived process spawned at session start; its CODE still needs that
# process restarted. Hooks are re-exec'd per prompt, which is exactly why they can hot-reload.

set -eu

REPO="$(cd "$(dirname "$0")/.." && pwd)"
SRC_DIR="$REPO/plugin/scripts"
CACHE_ROOT="$HOME/.claude/plugins/cache/ruvnet-brain/ruvnet-brain"
MODE="${1:---status}"

[ -d "$SRC_DIR" ] || { echo "dev-plugin-link: no $SRC_DIR"; exit 2; }
[ -d "$CACHE_ROOT" ] || { echo "dev-plugin-link: plugin not installed at $CACHE_ROOT"; exit 2; }

# Every cached version dir — a running session may have pinned any of them, and we do not know which.
versions() { find "$CACHE_ROOT" -mindepth 1 -maxdepth 1 -type d | sort; }

is_shim() { grep -q 'RUVNET_BRAIN_DEV_SHIM' "$1" 2>/dev/null; }

write_shim() {
  target="$1"; name="$(basename "$target")"; frozen="$(dirname "$target")/${name%.sh}.frozen.sh"
  # Freeze the pristine copy exactly once; re-linking must never overwrite it with a shim.
  if [ ! -f "$frozen" ]; then cp "$target" "$frozen"; fi
  cat >"$target" <<SHIM
#!/bin/sh
# RUVNET_BRAIN_DEV_SHIM — generated by scripts/dev-plugin-link.sh. Do not edit.
# Delegates to the working tree so hook edits take effect on the NEXT prompt, no restart.
DEV="$SRC_DIR/$name"
if [ "\${RUVNET_BRAIN_DEV:-1}" = "1" ] && [ -r "\$DEV" ]; then
  # Point CLAUDE_PLUGIN_ROOT at the repo too, so version/skills resolve from the working tree.
  CLAUDE_PLUGIN_ROOT="$REPO/plugin"; export CLAUDE_PLUGIN_ROOT
  exec /bin/sh "\$DEV" "\$@"
fi
exec /bin/sh "$(dirname "$target")/${name%.sh}.frozen.sh" "\$@"
SHIM
  chmod +x "$target"
}

case "$MODE" in
  --link)
    n=0
    for v in $(versions); do
      [ -d "$v/scripts" ] || continue
      for f in "$v"/scripts/*.sh; do
        [ -f "$f" ] || continue
        case "$(basename "$f")" in *.frozen.sh) continue ;; esac
        [ -f "$SRC_DIR/$(basename "$f")" ] || continue   # only shim scripts the repo actually has
        write_shim "$f"; n=$((n + 1))
      done
    done
    echo "dev-plugin-link: linked $n script(s) across $(versions | wc -l | tr -d ' ') cached version(s)"
    echo "  live source: $SRC_DIR"
    echo "  hook edits now apply on the NEXT prompt — no exit/restart."
    ;;
  --unlink)
    n=0
    for v in $(versions); do
      for f in "$v"/scripts/*.frozen.sh; do
        [ -f "$f" ] || continue
        orig="${f%.frozen.sh}.sh"
        mv "$f" "$orig"; n=$((n + 1))
      done
    done
    echo "dev-plugin-link: restored $n pristine script(s)"
    ;;
  --status)
    for v in $(versions); do
      [ -d "$v/scripts" ] || continue
      shimmed=0; total=0
      for f in "$v"/scripts/*.sh; do
        case "$(basename "$f")" in *.frozen.sh) continue ;; esac
        total=$((total + 1)); is_shim "$f" && shimmed=$((shimmed + 1))
      done
      printf '  %-14s %s/%s shimmed\n' "$(basename "$v")" "$shimmed" "$total"
    done
    ;;
  *) echo "usage: dev-plugin-link.sh [--link|--unlink|--status]"; exit 2 ;;
esac
