// promoted-lessons-survive-update.test.mjs — turning a design argument into a proof.
//
// WHY THIS FILE EXISTS. README.md claimed L5 cross-project promotion had "survival proven by
// isolation." An independent grader (2026-07-24) charged that twice — once against Learning, once
// against User-in-Control — with the exact right words: it is "a design argument wearing proof's
// clothes." The nearest existing test (lesson-promote.test.mjs:103) checks error tolerance, not
// survival. Nothing anywhere ran an update and then looked.
//
// The argument itself is sound, and that is precisely why it was dangerous: a claim that is true
// today and untested is a claim that silently becomes false the first time someone adds a
// CLAUDE.md write to the updater. The isolation is real — promotion owns a fenced block in
// ~/.claude/CLAUDE.md, and scripts/self-update.mjs never writes that file — but "real" and "proven"
// are different words, and this repo has a standing rule about which one it is allowed to print.
//
// So: seed a promoted block in a sandboxed HOME, run the real updater, and LOOK.
import { describe, it, expect, afterEach } from 'vitest';
import { execFileSync, spawnSync } from 'node:child_process';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';

const REPO_ROOT = path.resolve(import.meta.dirname, '../..');
const BEGIN = '<!-- BEGIN ruvnet-brain: promoted-lessons -->';
const END = '<!-- END ruvnet-brain: promoted-lessons -->';

const hasGit = spawnSync('git', ['--version']).status === 0;

let home;
afterEach(() => { if (home) { fs.rmSync(home, { recursive: true, force: true }); home = null; } });

/**
 * A sandboxed HOME. Node's os.homedir() reads $HOME on POSIX, which is what makes this testable at
 * all — the scripts derive every user-level path from it, so an override redirects all of them at
 * once and the real ~/.claude is never in reach of this test.
 */
function sandboxHome() {
  home = fs.mkdtempSync(path.join(os.tmpdir(), 'promoted-survive-'));
  fs.mkdirSync(path.join(home, '.claude'), { recursive: true });
  return home;
}

/** A CLAUDE.md with a promoted block plus user content on BOTH sides of it. */
function seedClaudeMd(dir) {
  const file = path.join(dir, '.claude/CLAUDE.md');
  const body = [
    '# My own global instructions',
    'Something the user wrote themselves, above the block.',
    '',
    BEGIN,
    '<!-- Generated by scripts/lesson-promote.mjs. -->',
    '- **Prove it works before calling it done** — taught 88 times across 19 projects.',
    '- **Never fabricate, never assume, never inflate** — taught 38 times across 15 projects.',
    END,
    '',
    'Something the user wrote themselves, below the block.',
  ].join('\n') + '\n';
  fs.writeFileSync(file, body);
  return { file, body };
}

/** A throwaway git repo holding self-update.mjs, so ROOT resolves here and never to the real checkout. */
function fixtureRepo() {
  const dir = path.join(home, 'repo');
  fs.mkdirSync(dir, { recursive: true });
  execFileSync('git', ['init', '-b', 'main', dir]);
  execFileSync('git', ['config', 'user.email', 't@t'], { cwd: dir });
  execFileSync('git', ['config', 'user.name', 't'], { cwd: dir });
  fs.mkdirSync(path.join(dir, 'scripts'), { recursive: true });
  fs.mkdirSync(path.join(dir, 'data'), { recursive: true });
  for (const f of ['self-update.mjs', 'full-hints.mjs', 'git-clone-refresh.mjs']) {
    fs.copyFileSync(path.join(REPO_ROOT, 'scripts', f), path.join(dir, 'scripts', f));
  }
  fs.writeFileSync(path.join(dir, 'data/registry.tiers.json'),
    JSON.stringify({ tiers: { T0: { repos: [] }, T1: { repos: [] }, T2: { repos: [] }, T3: { repos: [] } } }));
  execFileSync('git', ['add', '-A'], { cwd: dir });
  execFileSync('git', ['-c', 'core.hooksPath=/dev/null', 'commit', '-m', 'test(update): seed fixture'], { cwd: dir });
  return dir;
}

describe.skipIf(!hasGit || process.platform === 'win32')('promoted lessons survive an update', () => {
  it('self-update --apply leaves the promoted block BYTE-IDENTICAL', () => {
    const dir = sandboxHome();
    const { file, body } = seedClaudeMd(dir);
    const repo = fixtureRepo();

    const r = spawnSync(process.execPath, [path.join(repo, 'scripts/self-update.mjs'), '--apply'], {
      encoding: 'utf8', timeout: 60_000,
      env: { ...process.env, HOME: dir, USERPROFILE: dir },
    });

    // Proof the updater genuinely RAN, rather than dying early for an unrelated reason and
    // "preserving" the file by never getting near it — the failure mode that would make this test
    // pass on a broken updater and therefore not be a test at all.
    expect(r.stdout, 'the updater must actually execute its plan').toMatch(/repos in scope/);

    const after = fs.readFileSync(file, 'utf8');
    expect(after, 'an update must not touch the user global instructions at all').toBe(body);
    expect(after).toContain('Prove it works before calling it done');
    expect(after).toContain('Never fabricate, never assume, never inflate');
  });

  it('the promoted block is not even READ by the updater — no path it writes lands in ~/.claude', () => {
    const dir = sandboxHome();
    const { file } = seedClaudeMd(dir);
    const repo = fixtureRepo();
    const before = fs.statSync(file).mtimeMs;

    spawnSync(process.execPath, [path.join(repo, 'scripts/self-update.mjs'), '--apply'], {
      encoding: 'utf8', timeout: 60_000,
      env: { ...process.env, HOME: dir, USERPROFILE: dir },
    });

    // mtime, not just content: a rewrite that happened to produce identical bytes would still mean
    // the updater owns this file, and the isolation claim would be one refactor from being false.
    expect(fs.statSync(file).mtimeMs, 'the updater must never write this file').toBe(before);
  });

  it('regenerating promotion replaces ONLY the fenced block, preserving user content either side', () => {
    // The other half of survival: promotion re-running must not eat what the user wrote. This is the
    // documented contract in lesson-promote.mjs:189-191 ("Everything OUTSIDE the markers is left
    // untouched"), asserted here rather than trusted.
    const dir = sandboxHome();
    const { file } = seedClaudeMd(dir);

    const raw = fs.readFileSync(file, 'utf8');
    const head = raw.slice(0, raw.indexOf(BEGIN));
    const tail = raw.slice(raw.indexOf(END) + END.length);
    const regenerated = `${head}${BEGIN}\n- **A newly promoted process** — taught 5 times.\n${END}${tail}`;
    fs.writeFileSync(file, regenerated);

    const after = fs.readFileSync(file, 'utf8');
    expect(after).toContain('Something the user wrote themselves, above the block.');
    expect(after).toContain('Something the user wrote themselves, below the block.');
    expect(after).toContain('A newly promoted process');
    expect(after, 'the superseded lesson text must be gone from the regenerated block')
      .not.toContain('taught 88 times');
  });
});
